"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _credits_tab from './credits-tab.bones.json'
import _profile_tab from './profile-tab.bones.json'
import _settings_tab from './settings-tab.bones.json'
import _user_resumes from './user-resumes.bones.json'

registerBones({
  "credits-tab": _credits_tab,
  "profile-tab": _profile_tab,
  "settings-tab": _settings_tab,
  "user-resumes": _user_resumes,
})
